app/coastserv/main/routes.py
from flask import Blueprint
from flask import render_template, request
from flask import url_for, current_app
from flask import send_file, Response
from flask import after_this_request
import os
import zipfile
main = Blueprint('main', __name__)
import shutil



@main.route('/')
@main.route('/home')
def home():
	return render_template('home.html')


# @main.route('/downloads')
# def downloads():
#
# 	ziptidefile =os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static', 'out', 'tide.zip'))
# 	zipbcfile = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static', 'out', 'bc.zip'))
# 	zipextfile = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static', 'out', 'ext.zip'))
# 	allzips = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static', 'out', 'all.zip'))
# 	with zipfile.ZipFile(allzips, 'w') as zf:
# 		fullpath = ziptidefile
# 		zf.write(fullpath, os.path.basename(fullpath))
# 		fullpath = zipbcfile
# 		zf.write(fullpath, os.path.basename(fullpath))
# 		fullpath = zipextfile
# 		zf.write(fullpath, os.path.basename(fullpath))
#
# 	@after_this_request
# 	def remove_file(response):
# 		outdir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static', 'out'))
# 		shutil.rmtree(outdir)
# 		print('removed output directory', outdir)
# 		return response
#
#
# 	return send_file(allzips, attachment_filename='downloads.zip', as_attachment=True)

app/coastserv/requests/routes.py
from flask import render_template, url_for, flash, redirect, abort, current_app, request
from coastserv import db
from coastserv.requests.forms import RequestForm
from coastserv.models.model import Model
from coastserv.models.query import Query
from coastserv.models.tide import Tide
from coastserv.models.boundary import Boundary
from coastserv.models.units.units import usefor
from flask import after_this_request
from flask import send_file, Response
from flask import session
import shutil

import os
import json
import numpy as np
import pandas as pd
import coastserv.models.utils as utils
from flask import Blueprint
from azure.storage.file import FileService
import zipfile

# file_service = FileService(account_name='coastservstorage', account_key='HOBOcLV1nEDevDKfHMVq9N0TsgNrh4AXI2Qyxt4QAmvDi+oSUD9R6xnI8UEz7AVduzMill3+ymlNlj11jC58vw==')
# generator = file_service.list_directories_and_files('static')
# for file_or_dir in generator:
#     print(file_or_dir.name)


requests = Blueprint('requests', __name__)

@requests.route('/request', methods = ['GET', 'POST'])
def new_request():
	
	form = RequestForm()

	if form.validate_on_submit():
		flash('Form was deemed valid', 'success')

		name = form.name.data

		tstart = form.tstart.data
		tend = form.tend.data
		tref = form.tref.data
		xmin = form.xmin.data
		xmax = form.xmax.data
		ymin = form.ymin.data
		ymax = form.ymax.data

		username = form.username.data
		password = form.password.data
		dataset  = form.dataset.data

		pli_file = utils.save_pli_file(os.path.join(current_app.root_path, 'static','pli_files'), form.pli_file.data)

		model = Model(name = name, tstart = tstart, tend = tend , tref = tref, xmin= xmin, xmax = xmax, ymin = ymin, ymax = ymax, pli_file = pli_file, dataset = dataset, user = username)

		db.session.add(model)
		db.session.commit()

		# prepare for sending via url
		coords      = str([xmin, xmax, ymin, ymax])
		time_vect   = {"t_start" : tstart, "t_end" : tend}
		time_vect   = json.dumps(time_vect)
		credentials = {"user" : username, "pwd" : password}
		credentials = json.dumps(credentials)

		return redirect(url_for('requests.processing_query', name = name, time_vect = time_vect, tref = tref, dataset = dataset, coords = coords, pli_file = pli_file, credentials = credentials))

		
	return render_template('new_request.html', title = 'New Request', form = form, legend = 'New Request')


@requests.route('/processing_query', methods = ['GET', 'POST'])
def processing_query():
	'''
	for display/feedback purposes only
	'''
	name     = request.args.get('name')
	tref     = request.args.get('tref')
	dataset  = request.args.get('dataset')
	pli_file = request.args.get('pli_file')

	credentials = request.args.get('credentials') 
	time_vect   = request.args.get('time_vect')
	coords      = request.args.get('coords')

	return render_template('processing_query.html', name = name, time_vect = time_vect, tref = tref, dataset = dataset, coords = coords, pli_file = pli_file, credentials = credentials, legend = 'Processing Query')


@requests.route('/process', methods = ['GET', 'POST'])
def process():
	name     = request.args.get('name')
	# print(name)
	out = os.path.join(current_app.root_path, 'static', 'out')
	if not os.path.exists(out):
		os.mkdir(out)
	out = os.path.join(current_app.root_path, 'static','out', name)
	if not os.path.exists(out):
		os.mkdir(out)

	tref     = request.args.get('tref')
	dataset  = request.args.get('dataset')
	pli_file = request.args.get('pli_file')

	credentials = json.loads(request.args.get('credentials')) 
	time_vect = json.loads(request.args.get('time_vect'))
	coords = request.args.get('coords').replace('[','').replace(']','').split(',')
	coords = np.array(coords, dtype = np.float64)

	mod_query = Query(time_vect, dataset, coords, credentials, out)
	mod_query.build_query()

	fes_path = os.path.abspath(os.path.join(current_app.root_path, 'static', 'FES'))
	# file_service = FileService(account_name='coastservstorage',
	# 						   account_key='HOBOcLV1nEDevDKfHMVq9N0TsgNrh4AXI2Qyxt4QAmvDi+oSUD9R6xnI8UEz7AVduzMill3+ymlNlj11jC58vw==')
	# generator = file_service.list_directories_and_files('static/FES')
	# print('****************8testprinting848484848********************')
	# for file_or_dir in generator:
	# 	if file_or_dir.name == 'FES':
	# 		# fes_path3=file_or_dir.name
	# 		print(file_or_dir, file_or_dir.name)
	# 		# file_service.get_file_to_path('static/FES', None, file_or_dir.name, 'out.nc')
	mod_tide = Tide(fes_path, coords, pli_file, out)
	
	ext = mod_tide.ext
	data_list = os.path.join(out, 'data', '*.nc')
	
	# convert from CMEMS parameter names to DFM names

	CMEMS_subs = mod_query.all_subs[dataset]
	sub_list = []
	for sub in usefor.keys():
		if usefor[sub]['substance'][0] in CMEMS_subs:
			sub_list.append(sub)

	tref       = pd.Timestamp(tref).to_pydatetime()
	model_dir  = mod_tide.out
	mod_bound  = Boundary(ext, data_list, sub_list, tref, model_dir)

	return render_template('process.html', query = mod_query, tide = mod_tide, model = mod_bound, legend = 'Processing Query')

@requests.route('/downloads', methods = ['GET', 'POST'])
def downloads():

	ziptidefile =os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static', 'out', 'tide.zip'))
	zipbcfile = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static', 'out', 'bc.zip'))
	zipextfile = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static', 'out', 'ext.zip'))
	allzips = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static', 'out', 'all.zip'))
	with zipfile.ZipFile(allzips, 'w') as zf:
		fullpath = ziptidefile
		zf.write(fullpath, os.path.basename(fullpath))
		fullpath = zipbcfile
		zf.write(fullpath, os.path.basename(fullpath))
		fullpath = zipextfile
		zf.write(fullpath, os.path.basename(fullpath))

	@after_this_request
	def remove_file(response):
		outdir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static', 'out'))
		os.remove(ziptidefile)
		os.remove(zipbcfile)
		os.remove(zipextfile)
		os.remove(allzips)
		shutil.rmtree(outdir)
		session.clear()


		return response


	return send_file(allzips, attachment_filename='downloads.zip', as_attachment=True)

app/coastserv/templates/downloads.html

   <div class="container" align="left">
		<a href="/returnfiles/" target="blank"><button class='btn btn-default'>Download!</button></a>
   </div>


app/coastserv/templates/home.html
{% extends "layout.html" %}
{% block content %}
	<a class='btn btn-info mb-4' href="{{ url_for('requests.new_request') }}">New Request</a>
{% endblock content %}

app/coastserv/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
	
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	

		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

		{% if title %}
			<title>COASTSERV - {{ title }}</title>
		{% else %}
			<title>COASTSERV</title>
		{% endif %}

	</head>
	<body>
		<header class="site-header">
			<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
				<div class="container">
				<a class="navbar-brand mr-4" href="/">COASTSERV DEMO</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarToggle">
					<div class="navbar-nav mr-auto">
					<a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
					<a class="nav-item nav-link" href="{{ url_for('requests.downloads') }}">downloads</a>
				</div>
				</div>
			</nav>
		</header>

		<main role="main" class="container">
			<div class="row">
				<div class="col-md-8">
					<!--code to show flashed messages that have been activated>--> 
					{% with messages = get_flashed_messages(with_categories = true) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class='alert alert-{{ category }}'>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}	
					{% block content %}{% endblock %}
				</div>

			</div>
		</main>
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>

app/coastserv/templates/new_request.html
{% extends "layout.html" %}
{% block content %}

    <div class='content-section'>
        <form method="POST" action='' enctype = "multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'> {{ legend }}</legend>
                    <div class='form-group'>
                        {{ form.name.label(class='form-control-label') }}
                    
                        {% if form.name.errors %}
                            {{ form.name(class='form-control form-control-lg is-invalid')  }}
                            <div class='invalid-feedback'>
                                {% for error in form.name.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.name(class='form-control form-control-lg')  }}
                        {% endif %}
                    </div>        
                   <div class='form-group'>
                        {{ form.tstart.label(class='form-control-label') }}
                    
                        {% if form.tstart.errors %}
                            {{ form.tstart(class='form-control form-control-lg is-invalid')  }}
                            <div class='invalid-feedback'>
                                {% for error in form.tstart.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.tstart(class='form-control form-control-lg')  }}
                        {% endif %}
                    </div>
                    <div class='form-group'>
                        {{ form.tend.label(class='form-control-label') }}
                        {% if form.tend.errors %}
                            {{ form.tend(class='form-control form-control-lg is-invalid')  }}
                            <div class='invalid-feedback'>
                                {% for error in form.tend.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.tend(class='form-control form-control-lg')  }}
                        {% endif %}
                    </div>

                    <div class='form-group'>
                        {{ form.tref.label(class='form-control-label') }}
                        {% if form.tref.errors %}
                            {{ form.tref(class='form-control form-control-lg is-invalid')  }}
                            <div class='invalid-feedback'>
                                {% for error in form.tend.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.tref(class='form-control form-control-lg')  }}
                        {% endif %}
                    </div>

                    <div class='form-group'>
                        {{ form.xmin.label(class='form-control-label') }}
                        {% if form.xmin.errors %}
                            {{ form.xmin(class='form-control form-control-lg is-invalid')  }}
                            <div class='invalid-feedback'>
                                {% for error in form.xmin.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.xmin(class='form-control form-control-lg')  }}
                        {% endif %}
                    </div>

                    <div class='form-group'>
                        {{ form.xmax.label(class='form-control-label') }}
                        {% if form.xmax.errors %}
                            {{ form.xmax(class='form-control form-control-lg is-invalid')  }}
                            <div class='invalid-feedback'>
                                {% for error in form.xmax.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.xmax(class='form-control form-control-lg')  }}
                        {% endif %}
                    </div>
                    <div class='form-group'>
                        {{ form.ymin.label(class='form-control-label') }}
                        {% if form.ymin.errors %}
                            {{ form.ymin(class='form-control form-control-lg is-invalid')  }}
                            <div class='invalid-feedback'>
                                {% for error in form.ymin.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.ymin(class='form-control form-control-lg')  }}
                        {% endif %}
                    </div>
    
                    <div class='form-group'>
                        {{ form.ymax.label(class='form-control-label') }}
                        {% if form.ymax.errors %}
                            {{ form.ymax(class='form-control form-control-lg is-invalid')  }}
                            <div class='invalid-feedback'>
                                {% for error in form.ymax.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.ymax(class='form-control form-control-lg')  }}
                        {% endif %}
                    </div>

                    <div class='form-group'>
                        {{ form.pli_file.label() }}
                        {{ form.pli_file(class='form-control-file')}}
                        {% if form.pli_file.errors %}
                          {% for error in form.pli_file.errors %}
                            <span class="text-danger">
                              {{ error }}
                            </span>
                          {% endfor %}
                        {% endif %}
                    </div>      
                    
                    <div class='form-group'>
                        {{ form.dataset.label(class='form-control-label') }}
                        {% if form.dataset.errors %}
                            {{ form.dataset(class='form-control form-control-lg is-invalid')  }}
                            <div class='invalid-feedback'>
                                {% for error in form.dataset.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.dataset(class='form-control form-control-lg')  }}
                        {% endif %}
                    </div>  

                    <div class='form-group'>
                        {{ form.username.label(class='form-control-label') }}
                        {% if form.username.errors %}
                            {{ form.username(class='form-control form-control-lg is-invalid')  }}
                            <div class='invalid-feedback'>
                                {% for error in form.username.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class='form-control form-control-lg')  }}
                        {% endif %}
                    </div>
    
                    <div class='form-group'>
                        {{ form.password.label(class='form-control-label') }}
                        {% if form.password.errors %}
                            {{ form.password(class='form-control form-control-lg is-invalid')  }}
                            <div class='invalid-feedback'>
                                {% for error in form.password.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class='form-control form-control-lg')  }}
                        {% endif %}
                    </div>
                                        

            </fieldset>
            <div class='form-group'>
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>

{% endblock content %}

app/coastserv/templates/process.html
{% extends "layout.html" %}
{% block content %}
    <div class='content-section'>
        {{ query.send_request() }}
        {{ tide.build_tide() }}
        {{ model.build_boundary(interp = True, simultaneous = True, steric = False) }}
        
        <h1>Finished!</h1>
        <a class='btn btn-secondary btn-sm mt-1 mb-1' href= "{{ url_for('main.home') }}"> Finished, return home </a>
    </div>
{% endblock content %}

app/coastserv/templates/processing_query.html
{% extends "layout.html" %}
{% block content %}
    <div class='content-section'>
        <h1>COASTSERV is prepared to send your request to the CMEMS server.</h1>
        <a class='btn btn-secondary btn-sm mt-1 mb-1' href= "{{ url_for('requests.process', name = name, time_vect = time_vect, tref = tref, dataset = dataset, coords = coords, pli_file = pli_file, credentials = credentials) }}"> Execute processing </a>
    </div>
{% endblock content %}